This is example 3.8 on page 109 of [Quantitative Ecotoxicology](http://www.crcpress.com/product/isbn/9781439835647) - reproduced with R. This example is about accumulation and elimination of bromophos from water in a guppy (*Poecilia reticulata*).

There are two data files for this example - one for the [accumulation](https://raw.github.com/EDiLD/r-ed/master/quantitative_ecotoxicology/data/p109_accum.csv) and on for the [elimination](https://raw.github.com/EDiLD/r-ed/master/quantitative_ecotoxicology/data/p109_elimin.csv).


### Accumulation
First we will look at the accumulation phase:

```r
require(RCurl)
# Accumulation
url_accum <- getURL("https://raw.github.com/EDiLD/r-ed/master/quantitative_ecotoxicology/data/p109_accum.csv",
ssl.verifypeer = FALSE)
ACCUM <- read.table(text = url_accum, header = TRUE, sep = ";")
```


```r
head(ACCUM)
```

```
##   HOUR BRPHOS
## 1  0.5   1900
## 2  1.0   3000
## 3  2.0   5200
## 4  4.0   6900
## 5  8.0  24000
## 6 24.0  50000
```


Again we have two columns: One for the time and one for the concentration.


We fit can same model as in [example 3.7](http://edild.github.com/blog/2013/02/24/quant-ecotox-11/) to this data. The uptake $(k_u)$ and elimination $(k_e)$ constants are estimated simultaneously (at the same time):



```r
mod_accum <- nls(BRPHOS ~ KU/KE * 10.5 * (1 - exp(-KE * HOUR)), data = ACCUM, 
    start = list(KU = 100, KE = 0.01))
```

Note that I used different starting values than in the SAS-Code (must be a typo in the book). Also I didn't specify any bounds.

```r
summary(mod_accum)
```

```
## 
## Formula: BRPHOS ~ KU/KE * 10.5 * (1 - exp(-KE * HOUR))
## 
## Parameters:
##     Estimate Std. Error t value Pr(>|t|)    
## KU 344.79786   31.85529   10.82  4.7e-06 ***
## KE   0.00525    0.00103    5.09  0.00094 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
## 
## Residual standard error: 18900 on 8 degrees of freedom
## 
## Number of iterations to convergence: 7 
## Achieved convergence tolerance: 3.78e-06
```



```r
HOUR_pred <- seq(min(ACCUM$HOUR), max(ACCUM$HOUR), by = 0.1)
# Raw data
plot(ACCUM, main = "Accumulation")
# add model
lines(HOUR_pred, predict(mod_accum, newdata = data.frame(HOUR = HOUR_pred)))
```

<img src="figure/plot_accum_model.png" title="plot of chunk plot_accum_model" alt="plot of chunk plot_accum_model" width="400px" />


So from the accumulation data we estimated the uptake and elimination constants as:

* $k_e = 0.0053 \pm 0.0010$
* $k_u = 344.798 \pm 31.855$




### Sequential estimation
However we could also estimate the elimination constant $(k_e)$ from the elimination phase and then use this estimate for our accumulation data. 

* First estimate $k_e$ from a linear model (linear transformation)
* Plug this estimated $k_e$ into a nonlinear model to estimate $k_u$



```r
# Elimination data
url_elimin <- getURL("https://raw.github.com/EDiLD/r-ed/master/quantitative_ecotoxicology/data/p109_elimin.csv")
ELIMIN <- read.table(text = url_elimin, header = TRUE, sep = ";")
```


```r
head(ELIMIN)
```

```
##   HOUR BRPHOS
## 1    0 500000
## 2   12 450000
## 3   24 370000
## 4   48 290000
## 5   72 190000
## 6   96 150000
```

```r
plot(ELIMIN)
```

<img src="figure/plot_elimin_raw.png" title="plot of chunk plot_elimin_raw" alt="plot of chunk plot_elimin_raw" width="400px" />



We will estimate $k_e$ from a linear model like in [previous examples](http://edild.github.com/blog/2013/02/24/quant-ecotox-10/). We could also use nls for this.

First we need to transform the bromophos-concentration to linearize the relationship.

```r
ELIMIN$LBROMO <- log(ELIMIN$BRPHOS)
```


The we can use lm() to fit the linear model:

```r
mod_elimin_lm <- lm(LBROMO ~ HOUR, data = ELIMIN)
summary(mod_elimin_lm)
```

```
## 
## Call:
## lm(formula = LBROMO ~ HOUR, data = ELIMIN)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.09025 -0.03880 -0.00931  0.05900  0.11601 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 13.21262    0.03604   366.6  3.0e-16 ***
## HOUR        -0.01469    0.00025   -58.7  1.1e-10 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
## 
## Residual standard error: 0.0752 on 7 degrees of freedom
## Multiple R-squared: 0.998,	Adjusted R-squared: 0.998 
## F-statistic: 3.44e+03 on 1 and 7 DF,  p-value: 1.09e-10
```


So we get an estimate of $k_e$ as $0.0147 \pm 0.0003$.

This is quite different to the $k_e$ estimated simultaneous from the accumulation data!
Our linear model fits very good (R^2 = 0.998, no pattern in the residuals), so something is strange here...

```r
par(mfrow = c(1, 2))
# plot linearized model
plot(LBROMO ~ HOUR, data = ELIMIN, main = "Data + Model")
# add regression line
abline(mod_elimin_lm)
# plot residuals
plot(fitted(mod_elimin_lm), residuals(mod_elimin_lm), main = "Residuals")
abline(h = 0, lty = "dotted")
```

<img src="figure/elimin_diag.png" title="plot of chunk elimin_diag" alt="plot of chunk elimin_diag" width="400px" />



### Plug $k_e$ from the elimination phase into the accumulation model

Lets take $k_e$ from the elimination phase and plug it into our accumulation model and investigate the differences:


```r
mod_accum2 <- nls(BRPHOS ~ KU/-coef(mod_elimin_lm)[2] * 10.5 * (1 - exp(coef(mod_elimin_lm)[2] * 
    HOUR)), data = ACCUM, start = list(KU = 100))
summary(mod_accum2)
```

```
## 
## Formula: BRPHOS ~ KU/-coef(mod_elimin_lm)[2] * 10.5 * (1 - exp(coef(mod_elimin_lm)[2] * 
##     HOUR))
## 
## Parameters:
##    Estimate Std. Error t value Pr(>|t|)    
## KU    643.9       40.4    15.9  6.7e-08 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
## 
## Residual standard error: 51700 on 9 degrees of freedom
## 
## Number of iterations to convergence: 1 
## Achieved convergence tolerance: 5.27e-09
```


This estimates $k_u = 643.9 \pm 40.4$ which differs greatly from our initial results!
Lets plot this model and the residuals:

```r
par(mfrow = c(1, 2))
HOUR_pred <- seq(min(ACCUM$HOUR), max(ACCUM$HOUR), by = 0.1)
# Raw data
plot(ACCUM, main = "Accumulation")
# add model
lines(HOUR_pred, predict(mod_accum2, newdata = data.frame(HOUR = HOUR_pred)))
plot(fitted(mod_accum2), residuals(mod_accum2))
```

<img src="figure/plot_accum_model2.png" title="plot of chunk plot_accum_model2" alt="plot of chunk plot_accum_model2" width="400px" />



The residuals show a clear curve pattern. But we could also look at the residual sum of squares and the AIC to see which model fit better to the accumulation data:


```r
# Residual sum of squares
mod_accum$m$deviance()
```

```
## [1] 2870355583
```

```r
mod_accum2$m$deviance()
```

```
## [1] 24088396565
```

```r
# AIC
AIC(mod_accum)
```

```
## [1] 229.13
```

```r
AIC(mod_accum2)
```

```
## [1] 248.4
```


So the first model seem to better fit to the data. However see the discussion in the book for this example!

Once again we reproduced the results as in the book using R :)

Code and data are available on my [github-repo](https://github.com/EDiLD/r-ed/tree/master/quantitative_ecotoxicology) under file name 'p109'.

